# Default labels
- name: "breaking change"
  color: "b60205"

- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "dependencies"
  color: "1d76db"
  description: "Pull requests that update a dependency file"

- name: "DO NOT MERGE"
  color: "b60205"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "duplicate"
  color: "cfd8d7"
  description: "This issue or pull request already exists"

- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "good first issue"
  color: "fe9b9c"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "ignore for release"
  color: "bfd4f2"
  description: "Exclude from Release Notes"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "work in progress"
  color: "e5d19e"

# Type labels
- name: "@type/ci"
  color: "ededed"

- name: "@type/docs"
  color: "ededed"
  from_name: "documentation"

- name: "@type/feature"
  color: "ededed"

- name: "@type/fix"
  color: "ededed"

- name: "@type/improve"
  color: "ededed"
